apiVersion: apps/v1
kind: Deployment
metadata:
  name: restaurant-service
  namespace: cesieats-services
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: restaurant-service
  template:
    metadata:
      labels:
        app: restaurant-service
    spec:
      containers:
        - name: restaurant-service
          image: kilme/restaurant-service:$IMAGE_VERSION
          env:
          - name: DB_USERNAME
            valueFrom: 
              configMapKeyRef:
                name: mongodb-credentials
                key: username
          - name: DB_URL
            valueFrom: 
              configMapKeyRef:
                name: mongodb-credentials
                key: services-url
          - name: DB_PASSWORD
            valueFrom: 
              secretKeyRef:
                name: mongodb-credentials-secret
                key: password
          - name: RABBITMQ_USERNAME
            valueFrom: 
              configMapKeyRef:
                name: rabbitmq-credentials
                key: username
          - name: RABBITMQ_URL
            valueFrom: 
              configMapKeyRef:
                name: rabbitmq-credentials
                key: services-url
          - name: RABBITMQ_PASSWORD
            valueFrom: 
              secretKeyRef:
                name: rabbitmq-credentials-secret
                key: password
          resources:
            limits:
              memory: "512Mi"
              cpu: "250m"
          ports:
            - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: service-restaurant
  namespace: cesieats-services
spec:
  selector:
    app: restaurant-service
  ports:
    - name: http
      protocol: TCP
      port: 3000
      nodePort: 30108
  type: NodePort